name: CI Lint & Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
env:
  PNPM_STORE_PATH: "AppData\\Local\\pnpm-store"
  USERNAME: ""

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Send notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "content": "**Новый коммит в репозитории!**",
            "embeds": [{
              "title": "${{ github.repository }}",
              "description": "${{ github.event.head_commit.message }}",
              "url": "${{ github.event.head_commit.url }}",
              "timestamp": "${{ github.event.head_commit.timestamp }}",
              "footer": {
                "text": "${{ github.event.head_commit.author.name }}"
              },
              "color": 5814783
            }]
          }' ${{ secrets.DISCORD_WEBHOOK }}

      - name: Update USERNAME on env
        run: echo "USERNAME=$env:USERNAME" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Add "pnpm" in PATH
        run: echo "PATH=$(npm root -g)\pnpm:$env:Path" >> $GITHUB_ENV
        shell: pwsh

      - name: Check PATH and pnpm
        run: |
          echo $env:Path
          pnpm --version
        shell: pwsh

      - name: Install dependencies
        run: pnpm install
          
      - name: Cache usage 
        uses: actions/cache@v3 
        with: 
          path: "${{ env.USERNAME }}\\${{ env.PNPM_STORE_PATH }}" 
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }} 
          restore-keys: | 
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Run biome check
        run: npx biome check . --write

      - name: Run linter
        run: pnpm run lint

      - name: Run prettier check
        run: pnpm run format -- --check
