name: CI Lint & Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "content": "**Новый коммит в репозитории!**",
            "embeds": [{
              "title": "${{ github.repository }}",
              "description": "Коммит: ${{ github.event.head_commit.message }}",
              "url": "${{ github.event.head_commit.url }}",
              "color": 16711680
            }]
          }' ${{ secrets.DISCORD_WEBHOOK }}


      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Run biome check
        run: npx biome check . --write

      - name: Run linter
        run: pnpm run lint

      - name: Run prettier check
        run: pnpm run format -- --check
